<?php

class TestController {
    
    function actionIndex(){
      echo "<pre>";

        //$test = (json_decode('[["AMRAVATI ENCLAVE","CHANDIMANDIR","GH - 79","GH- 4 A","I T PARK","INDUSTRIAL AREA PH 2","INDUSTRIAL AREA PHASE 1","MANI MAJRA","MANSA DEVI COMPLEX","MODERN HOUSING CMPLX","NAC","RAIL VIHAR","RAJEEV VIHAR","SEC 5 MDC IN DLF CITY CENTRE CHANDHIGARH","SECTOR 10","SECTOR 11","SECTOR 12","SECTOR 12A","SECTOR 14","SECTOR 15","SECTOR 16","SECTOR 17","SECTOR 18","SECTOR 19","SECTOR 2","SECTOR 20","SECTOR 21","SECTOR 23","SECTOR 24","SECTOR 25","SECTOR 26","SECTOR 4","SECTOR 5","SECTOR 6","SECTOR 7","SECTOR 8","SECTOR 9","SWASTIK VIHAR"],["AMRAVATI ENCLAVE","CHANDIMANDIR","GH - 79","GH- 4 A","I T PARK","INDUSTRIAL AREA PH 2","INDUSTRIAL AREA PHASE 1","MANI MAJRA","MANSA DEVI COMPLEX","MODERN HOUSING CMPLX","NAC","RAIL VIHAR","RAJEEV VIHAR","SEC 5 MDC IN DLF CITY CENTRE CHANDHIGARH","SECTOR 10","SECTOR 11","SECTOR 12","SECTOR 12A","SECTOR 14","SECTOR 15","SECTOR 16","SECTOR 17","SECTOR 18","SECTOR 19","SECTOR 2","SECTOR 20","SECTOR 21","SECTOR 23","SECTOR 24","SECTOR 25","SECTOR 26","SECTOR 4","SECTOR 5","SECTOR 6","SECTOR 7","SECTOR 8","SECTOR 9","SWASTIK VIHAR"]]
//'));
        print_R($test);
      
       $areobj = new Area();
       //$areobj->addarea($test[0],5);
        die;

    }
}
?>
